project:
  type: website
  output-dir: docs

website:
  page-footer:
    left: |
      <div>{{< fa brands creative-commons >}} {{< var years >}} Elias Nelson Kaunda</div>
      <div>
        All content licensed under
        <a href="https://creativecommons.org/licenses/by/4.0/">
          {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} CC BY 4.0
        </a>
      </div>
    center: |
      <div>
        <i class="fab fa-orcid"></i> <strong>ORCID</strong>
        <a href="https://orcid.org/0009-0001-4918-0888">0009-0001-4918-0888</a>
      </div>
    right: |
      <div>
        Made with much patience, <i class="far fa-heart"></i>,
        <i class="fab fa-r-project"></i> and
        <a href="https://quarto.org/">
          <img src="https://quarto.org/quarto.png"
           alt="Quarto"
           style="height:1em; vertical-align:middle; margin-right:0.2em;">
        </a>
      </div>
      <div>
        <a href="https://github.com/elias-nelson/Quarto-Blog">
      View the source at <i class="fab fa-github"></i> GitHub
        </a>
      </div>
  title: "ENK"
  description: "This is Elias Nelson's personal Blog."
  favicon: "images/logo2.png"
  open-graph: true
  twitter-card: true
  page-navigation: true
  back-to-top-navigation: true
  search:
      location: navbar
      type: textbox
  comments: 
    utterances: 
      repo: elias-nelson/blogComments
      theme: github-light
      issue-term: title
  navbar:
    logo: 
      light: "/images/nav_bar_light.png"
      dark: "/images/nav_bar_dark.png"
    background: primary
    right:
      - text: "Home"
        aria-label: "Homepage"
        href: index.qmd
      - text: "Posts"
        aria-label: "List of Posts"
        href: posts/blog.qmd
      - text: "Gallery"
        href: gallery/gallery.qmd
      - text: "Software"
        href: software/software.qmd
      - icon: github
        href: https://github.com/elias-nelson/
      - icon: twitter-x
        href: https://x.com/iamelias_nelson
      - icon: instagram
        href: https://www.instagram.com/iamelias_nelson/
  #google-analytics: 
  #cookie-consent: 

lightbox: auto

format:
  html:
    toc: true
    theme:
      light:
        - cosmo
        - brand
        - assets/stylesheets/theme.scss
        - assets/stylesheets/projects.scss
      dark:
        - cosmo
        - brand
        - assets/stylesheets/theme.scss
        - assets/stylesheets/projects.scss
    # theme:
    #   light: [assets/li.scss]
    #   dark: [assets/da.scss]
    highlight-style: github
    css: assets/styles/styles.css
    html-math-method: katex
    clean-urls: false
     
editor: visual

